// fields that are for filtering
// everything not in select basically
export const filterSelection = [
  "league",
  "split",
  "playoffs",
  "date",
  "game",
  "patch",
  "side",
  "position",
  "teamname",
  "champion",
  "gamelength",
  "result",
  "opp_teamname",
]

export const filterBans = [
  "blue_ban1",
  "blue_ban2",
  "blue_ban3",
  "blue_ban4",
  "blue_ban5",
  "red_ban1",
  "red_ban2",
  "red_ban3",
  "red_ban4",
  "red_ban5",
]

export const filterPicks = [
  "blue_pick1",
  "blue_pick2",
  "blue_pick3",
  "blue_pick4",
  "blue_pick5",
  "red_pick1",
  "red_pick2",
  "red_pick3",
  "red_pick4",
  "red_pick5",
]

export const filterNumeric = [
  "opp_kills",
  "opp_deaths",
  "opp_assists",
  "opp_doublekills",
  "opp_triplekills",
  "opp_quadrakills",
  "opp_pentakills",
  "opp_ckpm",
  "opp_damagetochampions",
  "opp_dpm",
  "opp_damagetakenperminute",
  "opp_damagemitigatedperminute",
  "opp_wardsplaced",
  "opp_wpm",
  "opp_wardskilled",
  "opp_wcpm",
  "opp_controlwardsbought",
  "opp_visionscore",
  "opp_vspm",
  "opp_totalgold",
  "opp_earnedgold",
  "opp_earned_gpm",
  "opp_goldspent",
  "opp_minionkills",
  "opp_monsterkills",
  "opp_cspm",
  "opp_golddiffat10",
  "opp_xpdiffat10",
  "opp_csdiffat10",
  "opp_killsat10",
  "opp_assistsat10",
  "opp_deathsat10",
  "opp_golddiffat15",
  "opp_xpdiffat15",
  "opp_csdiffat15",
  "opp_killsat15",
  "opp_assistsat15",
  "opp_deathsat15",
  "opp_golddiffat20",
  "opp_xpdiffat20",
  "opp_csdiffat20",
  "opp_killsat20",
  "opp_assistsat20",
  "opp_deathsat20",
  "opp_golddiffat25",
  "opp_xpdiffat25",
  "opp_csdiffat25",
  "opp_killsat25",
  "opp_assistsat25",
  "opp_deathsat25",
]